name: invenman
description: "An Inventory Management App."
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  path_provider: any
  path: any
  provider: any
  intl: any
  shared_preferences: any
  sqflite_common_ffi: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
