name: ivenman
description: "Inventory Management App by Irrelevant"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0+4
  path_provider: ^2.1.2
  path: ^1.9.0
  provider: ^6.1.2
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
